fix resolve_itc_team_id Error: undefined method `[]' for nil:NilClass
When the developer_team name is accented (when it contains "é" or "è" for instance), we face this curious situation :
- Spaceship::Tunes.client.teams have unaccented developer_team name ("é" became "e")
- Spaceship::Portal.teams still have accented developer_team names
=> that's why comparing both names failed and itunes_team is nil, raising the "undefined method `[]' for nil:NilClass" error

With the use of I18n.transliterate we get rid of any accent related issues.

NB : this issue may come from the fact that when the developer_team name is accented its display is not consistent on apple websites :
- on appstoreconnect.apple.com it is unaccented ("é" => "e")
- on developer.apple.com it is still accented