[xdl][xde][exp] Make XDE use the Chromium HTTP stack with Axios (#1284)
* [XDL] Api/ApiV2 now using Axios instead of Request

* yarn

* Ready for PR

* fixes after review

* nit

* Ready for review P3

* removed console log

* Made requested changes + fixed FormData.js

* Remove unused variables

* Stop swallowing errors in Api.downloadAsync

* Download data as an ArrayBuffer

Avoid the extra Blob->ArrayBuffer conversion

* Add missing flow pragma

* Fix asset uploads and publishing from XDE

In order to use XMLHttpRequest and FormData to upload the asset files,
we must read them into a Blob. On Node.js, a read stream can be used
instead.

* Make use of paramsSerializer option of Axios

Simplify the query string handling code.

* Fix axios.request not being called w/o requestOptions

* Revert the removal of fs-mock-setup.js (removed in c5a62a7027d)

* [devtools] Fix API integration test

Apply similar changes as the UserManager changes here:
https://github.com/expo/universe/commit/533b9f7f51897801d198f3540fb95a14b05183d2

* [xdl] Make sure instapromise is imported in integration tests

instapromise adds functions such as fs.readFile.promise.

* [xdl] Ensure project (and ngrok) is stopped even if test fails

* [xdl] Increase timeout for API integration test

* Change fs.readFile.promise call, fix test failure?

This seems to fix the weird error
`TypeError: _fs.default.readFile.promise is not a function`
that happens while running in the integration tests.